parameters:
  start_date: '2013-01-01'
  end_date: '2026-02-03'
  period: D
  currency: EUR
paths:
  source_xlsx: X:\Quant\Data\ATLAS_data.xlsx
  output_xlsx: X:\Quant\Data\ATLAS_data_{universe}_static.xlsx
bloomberg:
  batch_size: 250
  ticker_suffix: ' Equity'
fields:
  price: PX_LAST
  Pxtobook: PX_TO_BOOK_RATIO
  EPS: IS_EPS
universes:
  default: sxxr
  available:
    - sxxr
    - nky
    - spx
    - pbh
    - sx5e
    - splpeqty
