parameters:
  start_date: '2013-01-01'
  end_date: '2026-02-03'
  period: D
  currency: EUR
paths:
  source_xlsx: X:\Quant\Data\ATLAS_data.xlsx
  output_xlsx: X:\Quant\Data\ATLAS_data_static.xlsx
bloomberg:
  batch_size: 250
  ticker_suffix: ' Equity'
fields:
  price: PX_LAST
  Pxtobook: PX_TO_BOOK_RATIO
  EPS: IS_EPS
tickers:
- 1816878D LN
- 1856607D IM
- 1986986D LN
- 1CNHI IM
- 3123739Q LN
- A2A IM
- AA/ LN
- AAK SS
- AAL LN
- AALB NA
- ABBN SE
- ABDN LN
- ABE SQ
- ABF LN
- ABG/P SQ
- ABI BB
- ABN NA
- AC FP
- ACA FP
- ACKB BB
- ACLN SE
- ACS SQ
- AD NA
- ADDTB SS
- ADEN SE
- ADEN SW
- ADM LN
- ADP FP
- ADS GY
- ADYEN NA
- AED BB
- AENA SQ
- AF FP
- AFX GY
- AG1 GY
- AGN NA
- AGS BB
- AHT LN
- AI FP
- AIBG ID
- AIR FP
- AKE FP
- AKRBP NO
- AKZA NA
- ALC SE
- ALE PW
- ALFA SS
- ALKB DC
- ALLFG NA
- ALLN SE
- ALO FP
- ALV GY
- AM FP
- AMBUB DC
- AMEAS FH
- AMFW LN
- AMP IM
- AMS SE
- AMS SQ
- AMUN FP
- ANA SQ
- ANDR AV
- ANTO LN
- ARCAD NA
- ARGX BB
- ARM LN
- ARYN SW
- ASHM LN
- ASM NA
- ASML NA
- ASRNL NA
- ASSAB SS
- ATCOA SS
- ATE FP
- ATL IM
- AUTO LN
- AV/ LN
- AVOL SE
- AXFO SS
- AZA SS
- AZE BB
- AZM IM
- AZN LN
- BA/ LN
- BAER SE
- BAER SW
- BAKKA NO
- BALDB SS
- BALN SE
- BAMI IM
- BAMNB NA
- BANB SE
- BARC LN
- BARN SE
- BAS GY
- BATS LN
- BAVA DC
- BAYN GY
- BB FP
- BBOX LN
- BBVA SQ
- BBY LN
- BC IM
- BC8 GY
- BCP PL
- BCVN SE
- BDEV LN
- BEAN SE
- BEI GY
- BEIJB SS
- BESI NA
- BEZ LN
- BG AV
- BGN IM
- BIM FP
- BION SE
- BIRG ID
- BKG LN
- BKT SQ
- BKW SE
- BLND LN
- BME LN
- BMED IM
- BMPS IM
- BMW GY
- BN FP
- BNP FP
- BNR GY
- BNZL LN
- BOKA NA
- BOL FP
- BOL SS
- BP IM
- BP/ LN
- BPE IM
- BPOST BB
- BPSO IM
- BPT LN
- BRBY LN
- BT/A LN
- BTG LN
- BTRW LN
- BUCN SE
- BUL IM
- BVI FP
- BVIC LN
- BWY LN
- BYG LN
- BZU IM
- CA FP
- CABK SQ
- CAP FP
- CARLB DC
- CAST SS
- CBG LN
- CBK GY
- CCC LN
- CCH LN
- CCL LN
- CDI FP
- CDR PW
- CFR SE
- CFR SW
- CLN SE
- CLN SW
- CLNX SQ
- CLS1 GY
- CMBN SE
- CNA LN
- CNP FP
- COFB BB
- COLOB DC
- COLR BB
- CON GY
- COTN SE
- COV FP
- CPG LN
- CPR IM
- CRDA LN
- CRH ID
- CS FP
- CSGN SW
- CTEC LN
- CVC NA
- CW/ LN
- CWC LN
- CWK LN
- DANSKE DC
- DB1 GY
- DBK GY
- DCC LN
- DEC FP
- DEMANT DC
- DG FP
- DGE LN
- DHER GY
- DHL GY
- DIA IM
- DIE BB
- DIM FP
- DKSH SE
- DLAR LN
- DLG LN
- DLN LN
- DNB NO
- DNP PW
- DPB GY
- DPLM LN
- DRX LN
- DSFIR NA
- DSM NA
- DSV DC
- DSY FP
- DTE GY
- DTG GY
- DUE GY
- DWNI GY
- EBS AV
- EDEN FP
- EDF FP
- EDP PL
- EDPR PL
- EKTAB SS
- EL FP
- ELE SQ
- ELI BB
- ELIS FP
- ELISA FH
- ELUXB SS
- EMBRACB SS
- EMG LN
- EMSN SE
- EN FP
- ENEL IM
- ENG SQ
- ENGI FP
- ENI IM
- ENR GY
- ENT LN
- ENTRA NO
- ENX FP
- EOAN GY
- EPIA SS
- EQNR NO
- EQT SS
- ERF FP
- ERICB SS
- ESSITYB SS
- ETL FP
- EVD GY
- EVK GY
- EVO SS
- EVT GY
- EXO NA
- EXPN LN
- EZJ LN
- F IM
- FBK IM
- FCC SQ
- FDJU FP
- FER SQ
- FGP LN
- FGR FP
- FHZN SE
- FLS DC
- FME GY
- FNOX SS
- FNTN GY
- FORTUM FH
- FPE3 GY
- FR FP
- FRA GY
- FRE GY
- FRES LN
- FRO NO
- FUR NA
- G IM
- G1A GY
- G24 GY
- GALD SE
- GALE SE
- GALP PL
- GAM SE
- GAW LN
- GBF GY
- GBLB BB
- GCC ID
- GEBN SE
- GEBN SW
- GET FP
- GETIB SS
- GF SE
- GFC FP
- GFTU LN
- GIVN SE
- GIVN SW
- GJF NO
- GLB ID
- GLE FP
- GLEN LN
- GMAB DC
- GN DC
- GRF SQ
- GRG LN
- GSK LN
- GTO FP
- GTT FP
- GXI GY
- HAG GY
- HBOS LN
- HEI GY
- HEIA NA
- HEIO NA
- HELN SE
- HEM SS
- HEN3 GY
- HER IM
- HEXAB SS
- HIAB FH
- HIK LN
- HL/ LN
- HLMA LN
- HLN LN
- HMB SS
- HMSO LN
- HNR1 GY
- HO FP
- HOLMB SS
- HOLN SE
- HOT GY
- HPOLB SS
- HSBA LN
- HSX LN
- HTO GA
- HUH1V FH
- HUSQB SS
- HWDN LN
- IAG LN
- IBE SQ
- ICG LN
- IDS LN
- IFCN SE
- IFX GY
- IG IM
- IGG LN
- IHG LN
- III LN
- IMB LN
- IMCD NA
- IMI LN
- INCH LN
- INDT SS
- INDUA SS
- INDUC SS
- INF LN
- ING FP
- INGA NA
- INPST NA
- INTU LN
- INVEB SS
- INVP LN
- INW IM
- IP IM
- IPN FP
- IPR LN
- ISAT LN
- ISP IM
- ISS DC
- ISYS LN
- ITRK LN
- ITV LN
- ITX SQ
- IVG IM
- JD/ LN
- JDEP NA
- JE/ LN
- JMAT LN
- JMT PL
- JUP LN
- JYSK DC
- KBC BB
- KBX GY
- KCR FH
- KD8 GY
- KEMIRA FH
- KER FP
- KESKOB FH
- KGF LN
- KGH PW
- KGX GY
- KINDSDB SS
- KINVB SS
- KNEBV FH
- KNIN SE
- KNIN SW
- KOG NO
- KOMB CK
- KPN NA
- KSP ID
- KYGA ID
- LAGRB SS
- LAND LN
- LATOB SS
- LDO IM
- LEG GY
- LGEN LN
- LHA GY
- LI FP
- LIFCOB SS
- LIGHT NA
- LISN SE
- LISP SE
- LLOY LN
- LMI LN
- LMP LN
- LNA GY
- LOGN SE
- LONN SE
- LOOMIS SS
- LOTB BB
- LPP PW
- LR FP
- LSEG LN
- LUNDB SS
- LXS GY
- MAB LN
- MAERSKB DC
- MANTA FH
- MAP SQ
- MB IM
- MBG GY
- MC FP
- MDC LN
- METSO FH
- MF FP
- MKS LN
- ML FP
- MNDI LN
- MNG LN
- MONC IM
- MOWI NO
- MRK GY
- MRL SQ
- MRO LN
- MRW LN
- MT NA
- MTX GY
- MUV2 GY
- MYCR SS
- NDA FH
- NDA GY
- NDA SS
- NEM GY
- NESN SE
- NESTE FH
- NEX FP
- NEXI IM
- NG/ LN
- NHY NO
- NIBEB SS
- NK FP
- NKT DC
- NN NA
- NOKIA FH
- NOVN SE
- NOVN SW
- NOVOB DC
- NSISB DC
- NTGY SQ
- NWG LN
- NXG LN
- NXT LN
- O2D GY
- OBEL BB
- OCDO LN
- OMV AV
- OPHR LN
- OR FP
- ORA FP
- ORK NO
- ORNBV FH
- ORRON SS
- ORSTED DC
- P911 GY
- PAH3 GY
- PEO PW
- PGHN SE
- PGS NO
- PHIA NA
- PHNX LN
- PKN PW
- PKO PW
- PLUS LN
- PNDORA DC
- PNL NA
- PNN LN
- PROX BB
- PRU LN
- PRX NA
- PRY IM
- PSM GY
- PSN LN
- PSON LN
- PSPN SE
- PST IM
- PTEC LN
- PUB FP
- PUIG SQ
- PUM GY
- PWTN SW
- PZU PW
- QIA GY
- QQ/ LN
- RAA GY
- RACE IM
- RAND NA
- RATOB SS
- RBI AV
- RBREW DC
- RCO FP
- RDC GY
- REC IM
- RED SQ
- REL LN
- REP SQ
- REY IM
- RF FP
- RGU LN
- RHA FP
- RHM GY
- RI FP
- RILBA DC
- RIO LN
- RKT LN
- RMS FP
- RMV LN
- RNO FP
- ROCKB DC
- ROG SE
- ROG SW
- ROR LN
- RR/ LN
- RRS LN
- RS1 LN
- RSA LN
- RTO LN
- RUI FP
- RUKN VX
- RWE GY
- RXL FP
- RYA ID
- SAABB SS
- SAB LN
- SAB SQ
- SAF FP
- SAFE LN
- SAGAB SS
- SALM NO
- SAMPO FH
- SAN FP
- SAN SQ
- SAND SS
- SAP GY
- SAVE SS
- SB1NO NO
- SBMO NA
- SBRY LN
- SCAB SS
- SCHP SE
- SCMN SE
- SCR FP
- SCT LN
- SCVB SS
- SDF GY
- SDR LN
- SDZ SE
- SEBA SS
- SECTB SS
- SECUB SS
- SESG FP
- SFSN SE
- SFZN SE
- SGC LN
- SGE LN
- SGO FP
- SGRO LN
- SGSN SE
- SHB LN
- SHBA SS
- SHC LN
- SHELL NA
- SHL GY
- SIE GY
- SIGN SE
- SIKA SE
- SK FP
- SKAB SS
- SKFB SS
- SKG ID
- SLHN SE
- SLHN SW
- SMDS LN
- SMIN LN
- SN/ LN
- SOBI SS
- SOF BB
- SOI FP
- SOON SE
- SOP FP
- SPIE FP
- SPL PW
- SPM IM
- SPR GY
- SPSN SE
- SPSN SW
- SPX LN
- SQN SE
- SREN SE
- SREN SW
- SRG IM
- SRP LN
- SRT3 GY
- SSABB SS
- SSE LN
- SSL LN
- SSPG LN
- STAN LN
- STB NO
- STERV FH
- STJ LN
- STLAM IM
- STMMI IM
- STMN SE
- SU FP
- SUBC NO
- SUN SE
- SUNN SE
- SVT LN
- SW FP
- SWECB SS
- SWEDA SS
- SWMA SS
- SXS LN
- SY1 GY
- SYDB DC
- SYENS BB
- TATE LN
- TBCG LN
- TCAP LN
- TCY LN
- TE FP
- TECN SE
- TEF SQ
- TEG GY
- TEL NO
- TEL2B SS
- TELIA SS
- TEMN SE
- TEN IM
- TEP FP
- THULE SS
- TIETO FH
- TIT IM
- TKA AV
- TKA GY
- TKWY NA
- TLX GY
- TNET BB
- TOM NO
- TPK LN
- TRELB SS
- TRN IM
- TRYG DC
- TSCO LN
- TTE FP
- TUB BB
- TUI1 GY
- TW/ LN
- TYRES FH
- UBI FP
- UBM LN
- UBSG SE
- UBSG SW
- UCB BB
- UCG IM
- UHR SE
- UHR SW
- ULE LN
- ULVR LN
- UMG NA
- UMI BB
- UN0 GY
- UNI IM
- UPM FH
- URW FP
- UTG LN
- UU/ LN
- VACN SE
- VALMT FH
- VAR NO
- VATN SE
- VCT LN
- VED LN
- VER AV
- VID SQ
- VIE FP
- VIFN SE
- VIS SQ
- VK FP
- VNA GY
- VOD LN
- VOE AV
- VOLVB SS
- VOW3 GY
- VPK NA
- VRLA FP
- VTG LN
- VTY LN
- VWS DC
- VZN SE
- WALLB SS
- WDP BB
- WEIR LN
- WIE AV
- WIHL SS
- WISE LN
- WKL NA
- WLN FP
- WMH LN
- WPP LN
- WRT1V FH
- WTB LN
- YAR NO
- ZAL GY
- ZEAL DC
- ZURN SE
